name: Deploy Static Site to S3 + CloudFront

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC - no secrets!)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::829779198710:role/github-actions-myweb   # ← CHANGE THIS
          aws-region: us-east-1


      - name: Create S3 bucket (safe if exists)
        run: aws s3 mb s3://mickeyfan01-myweb --region us-east-1 || echo "Bucket already exists"

      - name: Upload index.html to S3 (this is the key step you asked for)
        run: aws s3 sync . s3://mickeyfan01-myweb --delete --exclude ".git/*" --exclude ".github/*"

#      - name: Invalidate CloudFront cache
#        run: aws cloudfront create-invalidation --distribution-id YOUR-DISTRIBUTION-ID --paths "/*"   # ← CHANGE THIS
